#!/usr/bin/env php
<?php
/**
 * wpgen
 */

// Load composer autoloader.
// When installed globally via Composer, the autoloader lives up in the global vendor dir.
$autoloadPaths = [
    __DIR__ . '/vendor/autoload.php',           // Local development
    __DIR__ . '/../autoload.php',               // Installed as a dependency (vendor/bin/)
    __DIR__ . '/../../autoload.php',            // Installed as a dependency (vendor/package/bin/)
];

$autoloaderFound = false;
foreach ($autoloadPaths as $autoloadPath) {
    if (file_exists($autoloadPath)) {
        require $autoloadPath;
        $autoloaderFound = true;
        break;
    }
}

if (!$autoloaderFound) {
    fwrite(STDERR, "Could not find Composer autoloader. Run 'composer install' first.\n");
    exit(1);
}

// Declare application constants.
define( 'APP_ROOT', __DIR__ . '/' );

// Print application logo.
echo \WPGen\Config::get()->logo();

// Create application.
$app = new Symfony\Component\Console\Application();
$app->setName('wpgen');

// Get list of files in Commands directory.
$files = scandir( __DIR__ . '/src/Commands' );

// Exclude directories.
$files = array_diff( $files, ['.', '..', 'Traits'] );

// Register commands to application.
foreach( $files as $file ) {
    $class_name = str_replace( '.php', '', $file );
    $class_name = 'WPGen\\Commands\\' . $class_name;
    $app->add( new $class_name );
}

// Run application.
$app->run();